### ISSUE TITLE
allow eigenvector reading to use more threads than OMP_NUM_THREADS

### ISSUE THREAD

**Issue by kostrzewa** [kostrzewa/peram_gen#5]
@pittlerf I think we could make a dent in the unacceptable I/O time for eigenvectors if we allowed the eigenvector reading to use more threads than the rest of peram_gen.

**Comment by pittlerf** [comment]
As I see from the code, the reading does not use OMP parallelization at all. The first OMP pragma call is in line 85 in main.cpp.
